name: Vector Store Update

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  update-vector-store:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Deploy via SSH (vector store)
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ktb-user/20-real-ai
          git pull origin main
          source venv/bin/activate
          export GOOGLE_APPLICATION_CREDENTIALS="${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
          if ./vector_store.sh; then
            echo "✅ Vector store 생성 성공"
          else
            echo "❌ Vector store 생성 실패" && exit 1
          fi

    - name: Discord Notify
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        STATUS=${{ job.status }}
        RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        MESSAGE="🔔 AI 서버 Vector store 결과: **${STATUS}**\n📦 Repo: \`${{ github.repository }}\`\n🔁 Branch: \`${{ github.ref_name }}\`"
        if [ "$STATUS" != "success" ]; then
          MESSAGE="${MESSAGE}\n❌ [실패 로그 보러 가기](${RUN_URL})"
        fi
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"content\": \"${MESSAGE}\"}" \
             $DISCORD_WEBHOOK